---
- hosts: all
  tasks:
    - name: stop nginx
      service:
          name: {{ nginxname }}
          state: stopped
    - name: ensure nginx is not installed
      apt: name={{ nginxname }} state=absent
